---

- name: Install required packages (3.9)
  yum:
    name:
      - atomic-openshift-utils
      - docker-1.13.1
    state: present
  when: (openshift_version | string) == "3.9"
  become: yes

- name: Install required packages (3.10)
  yum:
    name:
      - openshift-ansible
      - docker-1.13.1
    state: present
  when: (openshift_version | string) == "3.10"
  become: yes

- name: Start and enable docker
  service:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Copy EC2 key
  copy:
    src: "{{ ec2_key_file }}"
    dest: ~/.ssh/id_rsa
    mode: 0600
    backup: yes
