---

- name: Create EC2 key pair
  ec2_key:
    name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    force: no
    state: present
  register: ec2_key

- name: Create keys directory
  file:
    path: "{{ keys_dir }}"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0700
  become: yes

- name: Output EC2 private key
  copy:
    dest: "{{ ec2_key_file }}"
    content: "{{ ec2_key.key.private_key }}"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600
  when: ec2_key.changed

- name: Set permissions for EC2 private key
  file:
    path: "{{ ec2_key_file }}"
    state: file
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600
  become: yes
