---

- name: Delete EC2 key pair
  ec2_key:
    name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    state: absent
  register: ec2_key

- name: Delete EC2 private key
  file:
    path: "{{ ec2_key_file }}"
    state: absent
