---

cluster_type: multi

app_node_count: 2

cns_storage_device: /dev/xvdb
cns_block_host_volume_size: 50

openshift_registry_volume_size: 20

openshift_network_plugin: redhat/openshift-ovs-networkpolicy
