---

openshift_public_hostname: "{{ cluster_name }}.{{ openshift_base_domain }}"

cluster_name_verbose: "{{ openshift_public_hostname | replace('.', '-') }}"
cluster_group_name: "{{ cluster_name_verbose | replace('-', '_') }}"

keys_dir: "{{ playbook_dir }}/keys"
ec2_key_name: "{{ openshift_public_hostname | replace('.', '-') }}"
ec2_key_file: "{{ keys_dir }}/{{ ec2_key_name }}.pem"

ec2_ami_ids:
  ap-south-1:
    cloud_access: ami-c2603bad
    hourly: ami-5b673c34
  eu-west-3:
    cloud_access: ami-5326902e
    hourly: ami-5026902d
  eu-west-2:
    cloud_access: ami-e81cfa8f
    hourly: ami-7c1bfd1b
  eu-west-1:
    cloud_access: ami-7776200e
    hourly: ami-7c491f05
  ap-northeast-2:
    cloud_access: ami-c213bfac
    hourly: ami-3eee4150
  ap-northeast-1:
    cloud_access: ami-2a0f5d4c
    hourly: ami-6b0d5f0d
  sa-east-1:
    cloud_access: ami-4cb2e620
    hourly: ami-b0b7e3dc
  ca-central-1:
    cloud_access: ami-09f3756d
    hourly: ami-49f0762d
  ap-southeast-1:
    cloud_access: ami-5a134c26
    hourly: ami-76144b0a
  ap-southeast-2:
    cloud_access: ami-3d5e935f
    hourly: ami-67589505
  eu-central-1:
    cloud_access: ami-526d3eb9
    hourly: ami-c86c3f23
  us-east-1:
    cloud_access: ami-0d70a070
    hourly: ami-6871a115
  us-east-2:
    cloud_access: ami-8f2617ea
    hourly: ami-03291866
  us-west-1:
    cloud_access: ami-e4716784
    hourly: ami-18726478
  us-west-2:
    cloud_access: ami-c6e27cbe
    hourly: ami-28e07e50
    
