---

- hosts: localhost
  roles:
    - host_facts_aws

- hosts: openshift_nodes:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  tasks:
  - name: Prepare all nodes for Istio
    include_role:
      name: host_prep_istio
  tags:
  - addon_istio

- hosts: openshift_role_master:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  tasks:
  - name: Install Istio using the master node
    include_role:
      name: install_istio
  tags:
  - addon_istio