---

- hosts: localhost
  roles:
    - provision_aws
    - host_facts_aws

- hosts: openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - rhsm_subscribe
    - host_prep_general

- hosts: openshift_nodes:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - host_prep_openshift

- hosts: openshift_bastion:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  any_errors_fatal: yes
  roles:
    - host_prep_bastion
    - install_openshift

- hosts: openshift_role_master:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  roles:
    - create_users
  tags:
    - openshift_deploy_cluster

- hosts: openshift_nodes:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  tasks:
  - name: Prepare all nodes for Istio
    include_role:
      name: host_prep_istio
    when: addon_istio
  tags:
  - addon_istio

- hosts: openshift_role_master:&openshift_cluster_{{ hostvars.localhost.cluster_group_name }}
  tasks:
  - name: Install Istio using the master node
    include_role:
      name: install_istio
    when: addon_istio
  tags:
  - addon_istio