---

# There is a current bug with DNSmasq causing things to fail during an
# OpenShift install. Installing/upgrading and then rebooting the nodes is
# the current workaround.
- name: Install/upgrade dnsmasq
  yum:
    name: dnsmasq
    state: latest
  register: install_update_dnsmasq
  become: yes

- block:
    - name: Reboot host
      shell: sleep 30 && shutdown -r now
      async: 30
      poll: 0
      ignore_errors: yes
      become: yes

    - name: Wait for nodes to boot
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 30
        timeout: 300
        search_regex: OpenSSH
      delegate_to: localhost
  when: install_update_dnsmasq.changed

- name: Install Docker
  yum:
    name: docker-1.13.1  # TODO: Make this a varible based on openshift_version
    state: present
  become: yes

- name: Write docker-storage-setup file
  template:
    src: docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644
  register: write_docker_storage_setup_file
  become: yes

- name: Run docker-storage-setup
  command: docker-storage-setup
  when: write_docker_storage_setup_file.changed
  become: yes

- name: Start and enable docker
  service:
    name: docker
    enabled: yes
    state: started
  become: yes
