---

openshift_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-ose-{{ openshift_version }}-rpms
  - rhel-7-fast-datapath-rpms
  - rhel-7-server-ansible-{{ ansible_repo_version }}-rpms

